version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: nestjs_pg
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - nest-network

volumes:
  postgres-data:

networks:
  nest-network: